### ISSUE TITLE
not a divide and conquer strategy

### ISSUE THREAD

**Issue by misael-diaz** [adcerro/closest-pair#15]
https://github.com/adcerro/closest-pair/blob/14b2e9097968cc68bcbc78f1bb9cd2ea46545fa0/Distance.java#L126

This is just a comment, not really an issue you need to solve.

Your implementation is not really applying the divide and conquer strategy. What it does is that it divides the original data in two parts and then applies brute force on both of them. What it should do is to divide until you get a partition of two or three points and only then you apply the brute force algorithm. You would also need a combination step to look for the closest pair between partitions.

I was hoping you would notice this and write about it in your report in (for example) an improvements section.

**Comment by adcerro** [comment]
comprendo, debo modificar el informe para hacer mención a eso en específico o pues ya así como está es aceptable?

**Comment by misael-diaz** [comment]
If you do, you should also say something about what needs to be done to fix the code. I recommend you to do that as soon as possible. Preferably no later than 6pm today.

**Comment by adcerro** [comment]
Por cierto profesor, disculpe que pregunte por acá pero, hasta cuando hay plazo para el laboratorio de linkedLists?, le escribí un correo al respecto

**Comment by misael-diaz** [comment]
the deadline was last Friday

**Comment by adcerro** [comment]
Comprendo, sé que no estoy en posición de pedirle que extienda el deadline un poquito más pues varios en el curso estamos hasta el cuello con parciales y entregas hasta la fecha de mañana y nos ha dificultado avanzar rápidamente en ese laboratorio pero  ¿pudiese extenderlo un poquito para poder entregárselo bien hecho?
